# Generated by Django 5.2.7 on 2025-11-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bill_bill_number_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.billingcycle'),
        ),
    ]
