# Generated by Django 5.2.7 on 2025-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bill_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
